### ISSUE TITLE
[TODO] Check the compatibility with Cython 3

### ISSUE THREAD

**Issue by webknjaz** [ansible/pylibssh#537]
Cython 3 has been stable for some time. We've been using v0.29.32 for building the wheels for release previously. https://github.com/ansible/pylibssh/pull/532 switched to v3.0.5.

Here's the differences to check: https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html.

**Comment by webknjaz** [comment]
@Qalthos could you confirm that none of the differences listed on that page matter to us?

**Comment by Qalthos** [comment]
I gave it a look over when I made the change, but I can give it another pass to make sure

**Comment by Qalthos** [comment]
I'm closing this as complete. The only two changes that could impact us at all are
* Python 3 syntax by default
* Changes to function binding

The former doesn't matter for us as we have been using Python 3 syntax since the start, and don't compile to Python 2 where weirdness might leak out. A quick perusal indicates that the very few literal strings we use that are not exception messages or dictionary keys are all properly encoded or decoded as appropriate.

The latter shouldn't affect us at all as far as I can tell.

The rest of the document is talking about things we simply do not use anywhere in the library.

**Comment by webknjaz** [comment]
Great, thanks for checking!
